# Generated by Django 3.2.9 on 2021-12-29 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_lesson_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='content',
            new_name='link',
        ),
    ]
