# Generated by Django 3.2.9 on 2021-12-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_rename_content_lesson_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='image',
        ),
    ]
