# Generated by Django 3.2.9 on 2021-12-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='user/default_user.png', upload_to='user/%Y/%m'),
        ),
    ]
